/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ServiceCategory = IDL.Variant({
  'postopcare' : IDL.Null,
  'ambulance' : IDL.Null,
  'elderlycare' : IDL.Null,
  'woundcare' : IDL.Null,
  'physiotherapy' : IDL.Null,
});
export const BookingStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'in_progress' : IDL.Null,
  'completed' : IDL.Null,
  'rejected' : IDL.Null,
  'accepted' : IDL.Null,
});
export const Booking = IDL.Record({
  'id' : IDL.Nat,
  'status' : BookingStatus,
  'latitude' : IDL.Float64,
  'scheduledDate' : IDL.Text,
  'scheduledTime' : IDL.Text,
  'nursePrincipal' : IDL.Opt(IDL.Principal),
  'createdAt' : IDL.Int,
  'estimatedFeeIdr' : IDL.Nat,
  'updatedAt' : IDL.Int,
  'visitReport' : IDL.Opt(IDL.Text),
  'patientPrincipal' : IDL.Principal,
  'longitude' : IDL.Float64,
  'notes' : IDL.Text,
  'serviceId' : IDL.Nat,
});
export const NurseStatus = IDL.Variant({
  'verified' : IDL.Null,
  'pending_verification' : IDL.Null,
  'rejected' : IDL.Null,
});
export const NurseProfile = IDL.Record({
  'status' : NurseStatus,
  'latitude' : IDL.Opt(IDL.Float64),
  'strNumber' : IDL.Text,
  'principal' : IDL.Principal,
  'locationUpdatedAt' : IDL.Opt(IDL.Int),
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'updatedAt' : IDL.Int,
  'experienceYears' : IDL.Nat,
  'strDocUrl' : IDL.Text,
  'longitude' : IDL.Opt(IDL.Float64),
  'ktpDocUrl' : IDL.Text,
  'specialization' : IDL.Text,
});
export const BookingStats = IDL.Record({
  'total' : IDL.Nat,
  'cancelled' : IDL.Nat,
  'pending' : IDL.Nat,
  'in_progress' : IDL.Nat,
  'completed' : IDL.Nat,
  'rejected' : IDL.Nat,
  'accepted' : IDL.Nat,
});
export const PatientProfile = IDL.Record({
  'age' : IDL.Nat,
  'principal' : IDL.Principal,
  'bloodType' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'emergencyContact' : IDL.Text,
  'updatedAt' : IDL.Int,
  'conditions' : IDL.Text,
  'allergies' : IDL.Text,
});
export const PricingAuditEntry = IDL.Record({
  'id' : IDL.Nat,
  'changedAt' : IDL.Int,
  'adminPrincipal' : IDL.Principal,
  'changeDescription' : IDL.Text,
});
export const PricingConfig = IDL.Record({
  'nightSurchargePct' : IDL.Nat,
  'holidaySurchargePct' : IDL.Nat,
  'updatedAt' : IDL.Int,
  'perKmRateIdr' : IDL.Nat,
});
export const Service = IDL.Record({
  'id' : IDL.Nat,
  'baseFeeIdr' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'updatedAt' : IDL.Int,
  'category' : ServiceCategory,
});

export const idlService = IDL.Service({
  'acceptBooking' : IDL.Func([IDL.Nat], [IDL.Text], []),
  'adminCreateService' : IDL.Func(
      [IDL.Text, IDL.Text, ServiceCategory, IDL.Nat],
      [IDL.Text],
      [],
    ),
  'adminDeleteService' : IDL.Func([IDL.Nat], [IDL.Text], []),
  'adminUpdatePricing' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Nat], [IDL.Text], []),
  'adminUpdateService' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Nat],
      [IDL.Text],
      [],
    ),
  'approveNurse' : IDL.Func([IDL.Principal], [IDL.Text], []),
  'cancelBooking' : IDL.Func([IDL.Nat], [IDL.Text], []),
  'createBooking' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Float64, IDL.Float64, IDL.Text],
      [IDL.Text],
      [],
    ),
  'estimateCost' : IDL.Func(
      [IDL.Nat, IDL.Float64, IDL.Bool, IDL.Bool],
      [IDL.Opt(IDL.Nat)],
      ['query'],
    ),
  'getAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getAllNurses' : IDL.Func([], [IDL.Vec(NurseProfile)], ['query']),
  'getBookingStats' : IDL.Func([], [IDL.Opt(BookingStats)], ['query']),
  'getIncomingBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getMyBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getMyNurseProfile' : IDL.Func([], [IDL.Opt(NurseProfile)], ['query']),
  'getMyPatientProfile' : IDL.Func([], [IDL.Opt(PatientProfile)], ['query']),
  'getMyRole' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
  'getNearbyNurses' : IDL.Func(
      [IDL.Float64, IDL.Float64, IDL.Float64],
      [IDL.Vec(NurseProfile)],
      ['query'],
    ),
  'getNurseProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(NurseProfile)],
      ['query'],
    ),
  'getNurseSchedule' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getPendingNurses' : IDL.Func([], [IDL.Vec(NurseProfile)], ['query']),
  'getPricingAuditLog' : IDL.Func([], [IDL.Vec(PricingAuditEntry)], ['query']),
  'getPricingConfig' : IDL.Func([], [PricingConfig], ['query']),
  'listAllServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
  'listServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
  'registerAsAdmin' : IDL.Func([], [IDL.Text], []),
  'registerAsNurse' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'registerAsPatient' : IDL.Func([], [IDL.Text], []),
  'rejectBooking' : IDL.Func([IDL.Nat], [IDL.Text], []),
  'rejectNurse' : IDL.Func([IDL.Principal], [IDL.Text], []),
  'saveNurseProfile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'savePatientProfile' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'seedDefaultServices' : IDL.Func([], [IDL.Text], []),
  'submitVisitReport' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Text], []),
  'updateNurseLocation' : IDL.Func([IDL.Float64, IDL.Float64], [IDL.Text], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ServiceCategory = IDL.Variant({
    'postopcare' : IDL.Null,
    'ambulance' : IDL.Null,
    'elderlycare' : IDL.Null,
    'woundcare' : IDL.Null,
    'physiotherapy' : IDL.Null,
  });
  const BookingStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'in_progress' : IDL.Null,
    'completed' : IDL.Null,
    'rejected' : IDL.Null,
    'accepted' : IDL.Null,
  });
  const Booking = IDL.Record({
    'id' : IDL.Nat,
    'status' : BookingStatus,
    'latitude' : IDL.Float64,
    'scheduledDate' : IDL.Text,
    'scheduledTime' : IDL.Text,
    'nursePrincipal' : IDL.Opt(IDL.Principal),
    'createdAt' : IDL.Int,
    'estimatedFeeIdr' : IDL.Nat,
    'updatedAt' : IDL.Int,
    'visitReport' : IDL.Opt(IDL.Text),
    'patientPrincipal' : IDL.Principal,
    'longitude' : IDL.Float64,
    'notes' : IDL.Text,
    'serviceId' : IDL.Nat,
  });
  const NurseStatus = IDL.Variant({
    'verified' : IDL.Null,
    'pending_verification' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const NurseProfile = IDL.Record({
    'status' : NurseStatus,
    'latitude' : IDL.Opt(IDL.Float64),
    'strNumber' : IDL.Text,
    'principal' : IDL.Principal,
    'locationUpdatedAt' : IDL.Opt(IDL.Int),
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'updatedAt' : IDL.Int,
    'experienceYears' : IDL.Nat,
    'strDocUrl' : IDL.Text,
    'longitude' : IDL.Opt(IDL.Float64),
    'ktpDocUrl' : IDL.Text,
    'specialization' : IDL.Text,
  });
  const BookingStats = IDL.Record({
    'total' : IDL.Nat,
    'cancelled' : IDL.Nat,
    'pending' : IDL.Nat,
    'in_progress' : IDL.Nat,
    'completed' : IDL.Nat,
    'rejected' : IDL.Nat,
    'accepted' : IDL.Nat,
  });
  const PatientProfile = IDL.Record({
    'age' : IDL.Nat,
    'principal' : IDL.Principal,
    'bloodType' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'emergencyContact' : IDL.Text,
    'updatedAt' : IDL.Int,
    'conditions' : IDL.Text,
    'allergies' : IDL.Text,
  });
  const PricingAuditEntry = IDL.Record({
    'id' : IDL.Nat,
    'changedAt' : IDL.Int,
    'adminPrincipal' : IDL.Principal,
    'changeDescription' : IDL.Text,
  });
  const PricingConfig = IDL.Record({
    'nightSurchargePct' : IDL.Nat,
    'holidaySurchargePct' : IDL.Nat,
    'updatedAt' : IDL.Int,
    'perKmRateIdr' : IDL.Nat,
  });
  const Service = IDL.Record({
    'id' : IDL.Nat,
    'baseFeeIdr' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'updatedAt' : IDL.Int,
    'category' : ServiceCategory,
  });
  
  return IDL.Service({
    'acceptBooking' : IDL.Func([IDL.Nat], [IDL.Text], []),
    'adminCreateService' : IDL.Func(
        [IDL.Text, IDL.Text, ServiceCategory, IDL.Nat],
        [IDL.Text],
        [],
      ),
    'adminDeleteService' : IDL.Func([IDL.Nat], [IDL.Text], []),
    'adminUpdatePricing' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Nat],
        [IDL.Text],
        [],
      ),
    'adminUpdateService' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Nat],
        [IDL.Text],
        [],
      ),
    'approveNurse' : IDL.Func([IDL.Principal], [IDL.Text], []),
    'cancelBooking' : IDL.Func([IDL.Nat], [IDL.Text], []),
    'createBooking' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Float64, IDL.Float64, IDL.Text],
        [IDL.Text],
        [],
      ),
    'estimateCost' : IDL.Func(
        [IDL.Nat, IDL.Float64, IDL.Bool, IDL.Bool],
        [IDL.Opt(IDL.Nat)],
        ['query'],
      ),
    'getAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getAllNurses' : IDL.Func([], [IDL.Vec(NurseProfile)], ['query']),
    'getBookingStats' : IDL.Func([], [IDL.Opt(BookingStats)], ['query']),
    'getIncomingBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getMyBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getMyNurseProfile' : IDL.Func([], [IDL.Opt(NurseProfile)], ['query']),
    'getMyPatientProfile' : IDL.Func([], [IDL.Opt(PatientProfile)], ['query']),
    'getMyRole' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
    'getNearbyNurses' : IDL.Func(
        [IDL.Float64, IDL.Float64, IDL.Float64],
        [IDL.Vec(NurseProfile)],
        ['query'],
      ),
    'getNurseProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(NurseProfile)],
        ['query'],
      ),
    'getNurseSchedule' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getPendingNurses' : IDL.Func([], [IDL.Vec(NurseProfile)], ['query']),
    'getPricingAuditLog' : IDL.Func(
        [],
        [IDL.Vec(PricingAuditEntry)],
        ['query'],
      ),
    'getPricingConfig' : IDL.Func([], [PricingConfig], ['query']),
    'listAllServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
    'listServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
    'registerAsAdmin' : IDL.Func([], [IDL.Text], []),
    'registerAsNurse' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'registerAsPatient' : IDL.Func([], [IDL.Text], []),
    'rejectBooking' : IDL.Func([IDL.Nat], [IDL.Text], []),
    'rejectNurse' : IDL.Func([IDL.Principal], [IDL.Text], []),
    'saveNurseProfile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'savePatientProfile' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'seedDefaultServices' : IDL.Func([], [IDL.Text], []),
    'submitVisitReport' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Text], []),
    'updateNurseLocation' : IDL.Func(
        [IDL.Float64, IDL.Float64],
        [IDL.Text],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };