/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Booking {
  'id' : bigint,
  'status' : BookingStatus,
  'latitude' : number,
  'scheduledDate' : string,
  'scheduledTime' : string,
  'nursePrincipal' : [] | [Principal],
  'createdAt' : bigint,
  'estimatedFeeIdr' : bigint,
  'updatedAt' : bigint,
  'visitReport' : [] | [string],
  'patientPrincipal' : Principal,
  'longitude' : number,
  'notes' : string,
  'serviceId' : bigint,
}
export interface BookingStats {
  'total' : bigint,
  'cancelled' : bigint,
  'pending' : bigint,
  'in_progress' : bigint,
  'completed' : bigint,
  'rejected' : bigint,
  'accepted' : bigint,
}
export type BookingStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'in_progress' : null } |
  { 'completed' : null } |
  { 'rejected' : null } |
  { 'accepted' : null };
export interface NurseProfile {
  'status' : NurseStatus,
  'latitude' : [] | [number],
  'strNumber' : string,
  'principal' : Principal,
  'locationUpdatedAt' : [] | [bigint],
  'name' : string,
  'createdAt' : bigint,
  'updatedAt' : bigint,
  'experienceYears' : bigint,
  'strDocUrl' : string,
  'longitude' : [] | [number],
  'ktpDocUrl' : string,
  'specialization' : string,
}
export type NurseStatus = { 'verified' : null } |
  { 'pending_verification' : null } |
  { 'rejected' : null };
export interface PatientProfile {
  'age' : bigint,
  'principal' : Principal,
  'bloodType' : string,
  'name' : string,
  'createdAt' : bigint,
  'emergencyContact' : string,
  'updatedAt' : bigint,
  'conditions' : string,
  'allergies' : string,
}
export interface PricingAuditEntry {
  'id' : bigint,
  'changedAt' : bigint,
  'adminPrincipal' : Principal,
  'changeDescription' : string,
}
export interface PricingConfig {
  'nightSurchargePct' : bigint,
  'holidaySurchargePct' : bigint,
  'updatedAt' : bigint,
  'perKmRateIdr' : bigint,
}
export interface Service {
  'id' : bigint,
  'baseFeeIdr' : bigint,
  'name' : string,
  'createdAt' : bigint,
  'description' : string,
  'isActive' : boolean,
  'updatedAt' : bigint,
  'category' : ServiceCategory,
}
export type ServiceCategory = { 'postopcare' : null } |
  { 'ambulance' : null } |
  { 'elderlycare' : null } |
  { 'woundcare' : null } |
  { 'physiotherapy' : null };
export interface _SERVICE {
  'acceptBooking' : ActorMethod<[bigint], string>,
  'adminCreateService' : ActorMethod<
    [string, string, ServiceCategory, bigint],
    string
  >,
  'adminDeleteService' : ActorMethod<[bigint], string>,
  'adminUpdatePricing' : ActorMethod<[bigint, bigint, bigint], string>,
  'adminUpdateService' : ActorMethod<[bigint, string, string, bigint], string>,
  'approveNurse' : ActorMethod<[Principal], string>,
  'cancelBooking' : ActorMethod<[bigint], string>,
  'createBooking' : ActorMethod<
    [bigint, string, string, number, number, string],
    string
  >,
  'estimateCost' : ActorMethod<
    [bigint, number, boolean, boolean],
    [] | [bigint]
  >,
  'getAllBookings' : ActorMethod<[], Array<Booking>>,
  'getAllNurses' : ActorMethod<[], Array<NurseProfile>>,
  'getBookingStats' : ActorMethod<[], [] | [BookingStats]>,
  'getIncomingBookings' : ActorMethod<[], Array<Booking>>,
  'getMyBookings' : ActorMethod<[], Array<Booking>>,
  'getMyNurseProfile' : ActorMethod<[], [] | [NurseProfile]>,
  'getMyPatientProfile' : ActorMethod<[], [] | [PatientProfile]>,
  'getMyRole' : ActorMethod<[], [] | [string]>,
  'getNearbyNurses' : ActorMethod<
    [number, number, number],
    Array<NurseProfile>
  >,
  'getNurseProfile' : ActorMethod<[Principal], [] | [NurseProfile]>,
  'getNurseSchedule' : ActorMethod<[], Array<Booking>>,
  'getPendingNurses' : ActorMethod<[], Array<NurseProfile>>,
  'getPricingAuditLog' : ActorMethod<[], Array<PricingAuditEntry>>,
  'getPricingConfig' : ActorMethod<[], PricingConfig>,
  'listAllServices' : ActorMethod<[], Array<Service>>,
  'listServices' : ActorMethod<[], Array<Service>>,
  'registerAsAdmin' : ActorMethod<[], string>,
  'registerAsNurse' : ActorMethod<
    [string, string, string, bigint, string, string],
    string
  >,
  'registerAsPatient' : ActorMethod<[], string>,
  'rejectBooking' : ActorMethod<[bigint], string>,
  'rejectNurse' : ActorMethod<[Principal], string>,
  'saveNurseProfile' : ActorMethod<
    [string, string, string, bigint, string, string],
    string
  >,
  'savePatientProfile' : ActorMethod<
    [string, bigint, string, string, string, string],
    string
  >,
  'seedDefaultServices' : ActorMethod<[], string>,
  'submitVisitReport' : ActorMethod<[bigint, string], string>,
  'updateNurseLocation' : ActorMethod<[number, number], string>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];