/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Article {
  'id' : bigint,
  'metaDescription' : string,
  'title' : string,
  'references' : Array<string>,
  'content' : string,
  'createdAt' : bigint,
  'slug' : string,
  'updatedAt' : bigint,
  'category' : string,
  'imagePrompt' : string,
}
export interface Booking {
  'id' : bigint,
  'status' : BookingStatus,
  'latitude' : number,
  'scheduledDate' : string,
  'scheduledTime' : string,
  'nursePrincipal' : [] | [Principal],
  'createdAt' : bigint,
  'estimatedFeeIdr' : bigint,
  'updatedAt' : bigint,
  'visitReport' : [] | [string],
  'patientPrincipal' : Principal,
  'longitude' : number,
  'notes' : string,
  'serviceId' : bigint,
}
export interface BookingStats {
  'total' : bigint,
  'cancelled' : bigint,
  'pending' : bigint,
  'in_progress' : bigint,
  'completed' : bigint,
  'rejected' : bigint,
  'accepted' : bigint,
}
export type BookingStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'in_progress' : null } |
  { 'completed' : null } |
  { 'rejected' : null } |
  { 'accepted' : null };
export interface NurseProfile {
  'previousWorkHistory' : [] | [string],
  'status' : NurseStatus,
  'latitude' : [] | [number],
  'strNumber' : string,
  'principal' : Principal,
  'emergencyCertExpiry' : [] | [string],
  'strExpiry' : [] | [string],
  'locationUpdatedAt' : [] | [bigint],
  'name' : string,
  'createdAt' : bigint,
  'profession' : [] | [string],
  'currentWorkDuration' : [] | [bigint],
  'graduationYear' : [] | [bigint],
  'strDocumentUrl' : [] | [string],
  'previousFacilityType' : [] | [string],
  'email' : [] | [string],
  'totalExperienceYears' : [] | [bigint],
  'university' : [] | [string],
  'additionalCertificates' : [] | [string],
  'ktpPhotoUrl' : [] | [string],
  'updatedAt' : bigint,
  'experienceYears' : bigint,
  'strDocUrl' : string,
  'currentFacilityType' : [] | [string],
  'longitude' : [] | [number],
  'ijazahDocumentUrl' : [] | [string],
  'ktpDocUrl' : string,
  'specialization' : string,
  'medicalCompetencies' : [] | [string],
  'passwordHash' : [] | [string],
  'selfieWithKtpUrl' : [] | [string],
  'emergencyCertification' : [] | [string],
  'employeeIdCardUrl' : [] | [string],
  'currentWorkplace' : [] | [string],
  'professionalOrg' : [] | [string],
}
export type NurseStatus = { 'verified' : null } |
  { 'pending_verification' : null } |
  { 'rejected' : null };
export interface PatientProfile {
  'age' : bigint,
  'nik' : [] | [string],
  'principal' : Principal,
  'bloodType' : string,
  'birthDate' : [] | [string],
  'name' : string,
  'createdAt' : bigint,
  'email' : [] | [string],
  'emergencyContactRelation' : [] | [string],
  'ktpPhotoUrl' : [] | [string],
  'updatedAt' : bigint,
  'address' : [] | [string],
  'gender' : [] | [string],
  'emergencyContactPhone' : [] | [string],
  'conditions' : string,
  'passwordHash' : [] | [string],
  'emergencyContactName' : [] | [string],
  'selfieWithKtpUrl' : [] | [string],
  'phoneNumber' : [] | [string],
  'allergies' : string,
  'verificationStatus' : string,
}
export interface PatientSummary {
  'nik' : string,
  'principal' : Principal,
  'fullName' : string,
  'submittedAt' : bigint,
  'selfieUrl' : string,
  'ktpPhotoUrl' : string,
  'verificationStatus' : string,
}
export interface PricingAuditEntry {
  'id' : bigint,
  'changedAt' : bigint,
  'adminPrincipal' : Principal,
  'changeDescription' : string,
}
export interface PricingConfig {
  'nightSurchargePct' : bigint,
  'holidaySurchargePct' : bigint,
  'updatedAt' : bigint,
  'perKmRateIdr' : bigint,
}
export type Result = { 'ok' : string } |
  { 'err' : string };
export type Result_1 = { 'ok' : bigint } |
  { 'err' : string };
export interface Service {
  'id' : bigint,
  'baseFeeIdr' : bigint,
  'name' : string,
  'createdAt' : bigint,
  'description' : string,
  'isActive' : boolean,
  'updatedAt' : bigint,
  'category' : ServiceCategory,
}
export type ServiceCategory = { 'postopcare' : null } |
  { 'ambulance' : null } |
  { 'elderlycare' : null } |
  { 'woundcare' : null } |
  { 'physiotherapy' : null };
export interface _SERVICE {
  'acceptBooking' : ActorMethod<[bigint], string>,
  'adminApprovePatient' : ActorMethod<[Principal], Result>,
  'adminCreateArticle' : ActorMethod<
    [string, string, string, string, string, Array<string>, string],
    Result_1
  >,
  'adminCreateService' : ActorMethod<
    [string, string, ServiceCategory, bigint],
    string
  >,
  'adminDeleteService' : ActorMethod<[bigint], string>,
  'adminRejectPatient' : ActorMethod<[Principal], Result>,
  'adminUpdateArticle' : ActorMethod<
    [bigint, string, string, string, string, Array<string>, string],
    Result
  >,
  'adminUpdatePricing' : ActorMethod<[bigint, bigint, bigint], string>,
  'adminUpdateService' : ActorMethod<[bigint, string, string, bigint], string>,
  'approveNurse' : ActorMethod<[Principal], string>,
  'cancelBooking' : ActorMethod<[bigint], string>,
  'createBooking' : ActorMethod<
    [bigint, string, string, number, number, string],
    string
  >,
  'estimateCost' : ActorMethod<
    [bigint, number, boolean, boolean],
    [] | [bigint]
  >,
  'getAllBookings' : ActorMethod<[], Array<Booking>>,
  'getAllNurses' : ActorMethod<[], Array<NurseProfile>>,
  'getAllPatients' : ActorMethod<[], Array<PatientProfile>>,
  'getArticleBySlug' : ActorMethod<[string], [] | [Article]>,
  'getBookingStats' : ActorMethod<[], [] | [BookingStats]>,
  'getIncomingBookings' : ActorMethod<[], Array<Booking>>,
  'getMyBookings' : ActorMethod<[], Array<Booking>>,
  'getMyNurseProfile' : ActorMethod<[], [] | [NurseProfile]>,
  'getMyPatientProfile' : ActorMethod<[], [] | [PatientProfile]>,
  'getMyRole' : ActorMethod<[], [] | [string]>,
  'getNearbyNurses' : ActorMethod<
    [number, number, number],
    Array<NurseProfile>
  >,
  'getNurseProfile' : ActorMethod<[Principal], [] | [NurseProfile]>,
  'getNurseSchedule' : ActorMethod<[], Array<Booking>>,
  'getPendingNurses' : ActorMethod<[], Array<NurseProfile>>,
  'getPendingPatients' : ActorMethod<[], Array<PatientSummary>>,
  'getPricingAuditLog' : ActorMethod<[], Array<PricingAuditEntry>>,
  'getPricingConfig' : ActorMethod<[], PricingConfig>,
  'listAllServices' : ActorMethod<[], Array<Service>>,
  'listArticles' : ActorMethod<
    [bigint, bigint],
    { 'total' : bigint, 'items' : Array<Article> }
  >,
  'listServices' : ActorMethod<[], Array<Service>>,
  'registerAsAdmin' : ActorMethod<[], string>,
  'registerAsNurse' : ActorMethod<
    [
      string,
      string,
      string,
      [] | [string],
      string,
      string,
      string,
      bigint,
      [] | [string],
      string,
      string,
      bigint,
      string,
      string,
      bigint,
      string,
      string,
      string,
      string,
      string,
      [] | [string],
      [] | [string],
      [] | [string],
    ],
    string
  >,
  'registerAsPatient' : ActorMethod<[], string>,
  'rejectBooking' : ActorMethod<[bigint], string>,
  'rejectNurse' : ActorMethod<[Principal], string>,
  'saveEmailPassword' : ActorMethod<[string, string], Result>,
  'saveNurseProfile' : ActorMethod<
    [
      string,
      string,
      string,
      [] | [string],
      string,
      string,
      string,
      bigint,
      [] | [string],
      string,
      string,
      bigint,
      string,
      string,
      bigint,
      string,
      string,
      string,
      string,
      string,
      [] | [string],
      [] | [string],
      [] | [string],
    ],
    string
  >,
  'savePatientProfile' : ActorMethod<
    [
      string,
      string,
      string,
      bigint,
      string,
      string,
      string,
      string,
      string,
      string,
      [] | [string],
      [] | [string],
      string,
      string,
      string,
    ],
    string
  >,
  'searchArticles' : ActorMethod<
    [string, bigint, bigint],
    { 'total' : bigint, 'items' : Array<Article> }
  >,
  'seedArticles' : ActorMethod<[], string>,
  'seedDefaultServices' : ActorMethod<[], string>,
  'submitVisitReport' : ActorMethod<[bigint, string], string>,
  'updateNurseLocation' : ActorMethod<[number, number], string>,
  'verifyEmailPassword' : ActorMethod<[string, string], Result>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];