/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Result_2 = {
    __kind__: "ok";
    ok: bigint;
} | {
    __kind__: "err";
    err: string;
};
export interface PatientSummary {
    nik: string;
    principal: Principal;
    fullName: string;
    submittedAt: bigint;
    selfieUrl: string;
    ktpPhotoUrl: string;
    verificationStatus: string;
}
export interface WalletBalance {
    userId: Principal;
    lastUpdated: bigint;
    balanceIdr: bigint;
}
export interface UserListEntry {
    status: string;
    name: string;
    role: string;
    email: string;
    registeredAt: bigint;
}
export interface Service {
    id: bigint;
    baseFeeIdr: bigint;
    name: string;
    createdAt: bigint;
    description: string;
    isActive: boolean;
    updatedAt: bigint;
    category: ServiceCategory;
}
export interface WalletTransaction {
    id: bigint;
    status: TransactionStatus;
    transactionType: TransactionType;
    userId: Principal;
    createdAt: bigint;
    description: string;
    currency: string;
    amount: bigint;
}
export interface PricingAuditEntry {
    id: bigint;
    changedAt: bigint;
    adminPrincipal: Principal;
    changeDescription: string;
}
export type Result_1 = {
    __kind__: "ok";
    ok: {
        role: string;
    };
} | {
    __kind__: "err";
    err: string;
};
export interface PlatformSettings {
    appName: string;
    maintenanceMode: boolean;
    supportEmail: string;
    supportPhone: string;
}
export interface BookingStats {
    total: bigint;
    cancelled: bigint;
    pending: bigint;
    in_progress: bigint;
    completed: bigint;
    rejected: bigint;
    accepted: bigint;
}
export type Result = {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "err";
    err: string;
};
export interface Pharmacy {
    id: bigint;
    lat: number;
    lon: number;
    closeTime: string;
    name: string;
    address: string;
    phone: string;
    drugs: Array<DrugStock>;
    openTime: string;
}
export interface TransactionEntry {
    id: bigint;
    status: string;
    transactionType: string;
    userId: Principal;
    createdAt: bigint;
    description: string;
    amount: bigint;
}
export interface PricingConfig {
    nightSurchargePct: bigint;
    holidaySurchargePct: bigint;
    updatedAt: bigint;
    perKmRateIdr: bigint;
}
export interface PatientProfile {
    age: bigint;
    nik?: string;
    principal: Principal;
    bloodType: string;
    birthDate?: string;
    name: string;
    createdAt: bigint;
    email?: string;
    emergencyContactRelation?: string;
    ktpPhotoUrl?: string;
    updatedAt: bigint;
    address?: string;
    gender?: string;
    emergencyContactPhone?: string;
    conditions: string;
    passwordHash?: string;
    emergencyContactName?: string;
    selfieWithKtpUrl?: string;
    phoneNumber?: string;
    allergies: string;
    verificationStatus: string;
}
export interface DrugStock {
    drugName: string;
    available: boolean;
    quantity: bigint;
    category: string;
    priceIdr: bigint;
}
export interface NurseProfile {
    previousWorkHistory?: string;
    status: NurseStatus;
    latitude?: number;
    strNumber: string;
    principal: Principal;
    emergencyCertExpiry?: string;
    strExpiry?: string;
    locationUpdatedAt?: bigint;
    name: string;
    createdAt: bigint;
    profession?: string;
    currentWorkDuration?: bigint;
    graduationYear?: bigint;
    strDocumentUrl?: string;
    previousFacilityType?: string;
    email?: string;
    totalExperienceYears?: bigint;
    university?: string;
    additionalCertificates?: string;
    ktpPhotoUrl?: string;
    updatedAt: bigint;
    experienceYears: bigint;
    strDocUrl: string;
    currentFacilityType?: string;
    longitude?: number;
    ijazahDocumentUrl?: string;
    ktpDocUrl: string;
    specialization: string;
    medicalCompetencies?: string;
    passwordHash?: string;
    selfieWithKtpUrl?: string;
    emergencyCertification?: string;
    employeeIdCardUrl?: string;
    currentWorkplace?: string;
    professionalOrg?: string;
}
export interface Booking {
    id: bigint;
    status: BookingStatus;
    latitude: number;
    scheduledDate: string;
    scheduledTime: string;
    nursePrincipal?: Principal;
    createdAt: bigint;
    estimatedFeeIdr: bigint;
    updatedAt: bigint;
    visitReport?: string;
    patientPrincipal: Principal;
    longitude: number;
    notes: string;
    serviceId: bigint;
}
export interface ActivityEntry {
    id: bigint;
    actorRole: string;
    metadata: string;
    actionType: string;
    description: string;
    timestamp: bigint;
    actorEmail: string;
}
export interface Article {
    id: bigint;
    metaDescription: string;
    title: string;
    references: Array<string>;
    content: string;
    createdAt: bigint;
    slug: string;
    updatedAt: bigint;
    category: string;
    imagePrompt: string;
}
export enum BookingStatus {
    cancelled = "cancelled",
    pending = "pending",
    in_progress = "in_progress",
    completed = "completed",
    rejected = "rejected",
    accepted = "accepted"
}
export enum DepositMethod {
    ovo = "ovo",
    dana = "dana",
    va_bca = "va_bca",
    va_bni = "va_bni",
    va_bri = "va_bri",
    va_mandiri = "va_mandiri"
}
export enum NurseStatus {
    verified = "verified",
    pending_verification = "pending_verification",
    rejected = "rejected"
}
export enum ServiceCategory {
    postopcare = "postopcare",
    ambulance = "ambulance",
    elderlycare = "elderlycare",
    woundcare = "woundcare",
    physiotherapy = "physiotherapy"
}
export enum TransactionStatus {
    pending = "pending",
    completed = "completed",
    failed = "failed"
}
export enum TransactionType {
    transfer_out = "transfer_out",
    deposit = "deposit",
    transfer_in = "transfer_in",
    withdrawal = "withdrawal",
    service_income = "service_income",
    service_payment = "service_payment"
}
export enum Variant_ok_notFound {
    ok = "ok",
    notFound = "notFound"
}
export enum Variant_ok_notFound_unauthorized {
    ok = "ok",
    notFound = "notFound",
    unauthorized = "unauthorized"
}
export enum WithdrawalMethod {
    ovo = "ovo",
    bank_mandiri = "bank_mandiri",
    dana = "dana",
    bank_bca = "bank_bca",
    bank_bni = "bank_bni",
    bank_bri = "bank_bri"
}
export interface backendInterface {
    acceptBooking(bookingId: bigint): Promise<string>;
    activateUser(targetEmail: string): Promise<Variant_ok_notFound>;
    adminAddPharmacy(name: string, address: string, lat: number, lon: number, openTime: string, closeTime: string, phone: string): Promise<Result_2>;
    adminApprovePatient(patientPrincipal: Principal): Promise<Result>;
    adminCreateArticle(slug: string, title: string, metaDescription: string, content: string, imagePrompt: string, references: Array<string>, category: string): Promise<Result_2>;
    adminCreateService(name: string, description: string, category: ServiceCategory, baseFeeIdr: bigint): Promise<string>;
    adminDeleteService(id: bigint): Promise<string>;
    adminGetAllWalletStats(): Promise<{
        totalVolume: bigint;
        pendingWithdrawals: bigint;
        totalUsers: bigint;
    }>;
    adminRejectPatient(patientPrincipal: Principal): Promise<Result>;
    adminUpdateArticle(id: bigint, title: string, metaDescription: string, content: string, imagePrompt: string, references: Array<string>, category: string): Promise<Result>;
    adminUpdatePharmacyStock(pharmacyId: bigint, items: Array<DrugStock>): Promise<Result>;
    adminUpdatePricing(perKmRateIdr: bigint, nightSurchargePct: bigint, holidaySurchargePct: bigint): Promise<string>;
    adminUpdateService(id: bigint, name: string, description: string, baseFeeIdr: bigint): Promise<string>;
    approveNurse(nursePrincipal: Principal): Promise<string>;
    cancelBooking(bookingId: bigint): Promise<string>;
    createBooking(serviceId: bigint, scheduledDate: string, scheduledTime: string, latitude: number, longitude: number, notes: string): Promise<string>;
    deleteUser(targetEmail: string): Promise<Variant_ok_notFound_unauthorized>;
    deposit(amount: bigint, method: DepositMethod): Promise<{
        __kind__: "ok";
        ok: WalletBalance;
    } | {
        __kind__: "err";
        err: string;
    }>;
    estimateCost(serviceId: bigint, distanceKm: number, nightTime: boolean, holiday: boolean): Promise<bigint | null>;
    getActivityLog(limit: bigint, offset: bigint): Promise<Array<ActivityEntry>>;
    getAdminFinancialReport(): Promise<{
        pendingWithdrawals: bigint;
        recentTransactions: Array<TransactionEntry>;
        totalWithdrawals: bigint;
        totalRevenue: bigint;
        transactionCount: bigint;
    }>;
    getAllBookings(): Promise<Array<Booking>>;
    getAllNurses(): Promise<Array<NurseProfile>>;
    getAllPatients(): Promise<Array<PatientProfile>>;
    getArticleBySlug(slug: string): Promise<Article | null>;
    getBookingStats(): Promise<BookingStats | null>;
    getIncomingBookings(): Promise<Array<Booking>>;
    getMyBalance(): Promise<WalletBalance>;
    getMyBookings(): Promise<Array<Booking>>;
    getMyNurseProfile(): Promise<NurseProfile | null>;
    getMyPatientProfile(): Promise<PatientProfile | null>;
    getMyRole(): Promise<string | null>;
    getMyTransactionHistory(): Promise<Array<WalletTransaction>>;
    getNearbyNurses(lat: number, lon: number, radiusKm: number): Promise<Array<NurseProfile>>;
    getNurseProfile(p: Principal): Promise<NurseProfile | null>;
    getNurseSchedule(): Promise<Array<Booking>>;
    getPendingNurses(): Promise<Array<NurseProfile>>;
    getPendingPatients(): Promise<Array<PatientSummary>>;
    getPharmacies(): Promise<Array<Pharmacy>>;
    getPharmacyDrugs(pharmacyId: bigint): Promise<Array<DrugStock>>;
    getPharmacyStock(pharmacyId: bigint): Promise<Array<DrugStock> | null>;
    getPlatformSettings(): Promise<PlatformSettings>;
    getPricingAuditLog(): Promise<Array<PricingAuditEntry>>;
    getPricingConfig(): Promise<PricingConfig>;
    getUserList(filterRole: string | null, filterStatus: string | null): Promise<Array<UserListEntry>>;
    listAllServices(): Promise<Array<Service>>;
    listArticles(page: bigint, pageSize: bigint): Promise<{
        total: bigint;
        items: Array<Article>;
    }>;
    listServices(): Promise<Array<Service>>;
    loginWithEmail(email: string, password: string): Promise<Result_1>;
    registerAsAdmin(): Promise<string>;
    registerAsNurse(name: string, strNumber: string, strExpiry: string, strDocumentUrl: string | null, specialization: string, profession: string, university: string, graduationYear: bigint, ijazahDocumentUrl: string | null, professionalOrg: string, previousWorkHistory: string, totalExperienceYears: bigint, previousFacilityType: string, currentWorkplace: string, currentWorkDuration: bigint, currentFacilityType: string, emergencyCertification: string, emergencyCertExpiry: string, additionalCertificates: string, medicalCompetencies: string, employeeIdCardUrl: string | null, ktpPhotoUrl: string | null, selfieWithKtpUrl: string | null): Promise<string>;
    registerAsPatient(): Promise<string>;
    rejectBooking(bookingId: bigint): Promise<string>;
    rejectNurse(nursePrincipal: Principal): Promise<string>;
    requestWithdrawal(amount: bigint, method: WithdrawalMethod, accountNumber: string): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }>;
    saveEmailPassword(email: string, password: string): Promise<Result>;
    saveNurseProfile(name: string, strNumber: string, strExpiry: string, strDocumentUrl: string | null, specialization: string, profession: string, university: string, graduationYear: bigint, ijazahDocumentUrl: string | null, professionalOrg: string, previousWorkHistory: string, totalExperienceYears: bigint, previousFacilityType: string, currentWorkplace: string, currentWorkDuration: bigint, currentFacilityType: string, emergencyCertification: string, emergencyCertExpiry: string, additionalCertificates: string, medicalCompetencies: string, employeeIdCardUrl: string | null, ktpPhotoUrl: string | null, selfieWithKtpUrl: string | null): Promise<string>;
    savePatientProfile(name: string, nik: string, birthDate: string, age: bigint, gender: string, address: string, phoneNumber: string, emergencyContactName: string, emergencyContactRelation: string, emergencyContactPhone: string, ktpPhotoUrl: string | null, selfieWithKtpUrl: string | null, conditions: string, allergies: string, bloodType: string): Promise<string>;
    searchArticles(searchQuery: string, page: bigint, pageSize: bigint): Promise<{
        total: bigint;
        items: Array<Article>;
    }>;
    seedArticles(): Promise<string>;
    seedDefaultServices(): Promise<string>;
    seedPharmacies(): Promise<string>;
    submitVisitReport(bookingId: bigint, reportText: string): Promise<string>;
    suspendUser(targetEmail: string, reason: string): Promise<Variant_ok_notFound_unauthorized>;
    transferBalance(toUserId: Principal, amount: bigint): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }>;
    updateNurseLocation(lat: number, lon: number): Promise<string>;
    updatePlatformSettings(settings: PlatformSettings): Promise<Result>;
    verifyEmailPassword(email: string, password: string): Promise<Result>;
}
import type { Article as _Article, Booking as _Booking, BookingStats as _BookingStats, BookingStatus as _BookingStatus, DepositMethod as _DepositMethod, DrugStock as _DrugStock, NurseProfile as _NurseProfile, NurseStatus as _NurseStatus, PatientProfile as _PatientProfile, Result as _Result, Result_1 as _Result_1, Result_2 as _Result_2, Service as _Service, ServiceCategory as _ServiceCategory, TransactionStatus as _TransactionStatus, TransactionType as _TransactionType, WalletBalance as _WalletBalance, WalletTransaction as _WalletTransaction, WithdrawalMethod as _WithdrawalMethod } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async acceptBooking(arg0: bigint): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.acceptBooking(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.acceptBooking(arg0);
            return result;
        }
    }
    async activateUser(arg0: string): Promise<Variant_ok_notFound> {
        if (this.processError) {
            try {
                const result = await this.actor.activateUser(arg0);
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.activateUser(arg0);
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminAddPharmacy(arg0: string, arg1: string, arg2: number, arg3: number, arg4: string, arg5: string, arg6: string): Promise<Result_2> {
        if (this.processError) {
            try {
                const result = await this.actor.adminAddPharmacy(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return from_candid_Result_2_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminAddPharmacy(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return from_candid_Result_2_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminApprovePatient(arg0: Principal): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.adminApprovePatient(arg0);
                return from_candid_Result_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminApprovePatient(arg0);
            return from_candid_Result_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminCreateArticle(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: Array<string>, arg6: string): Promise<Result_2> {
        if (this.processError) {
            try {
                const result = await this.actor.adminCreateArticle(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return from_candid_Result_2_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminCreateArticle(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return from_candid_Result_2_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminCreateService(arg0: string, arg1: string, arg2: ServiceCategory, arg3: bigint): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.adminCreateService(arg0, arg1, to_candid_ServiceCategory_n6(this._uploadFile, this._downloadFile, arg2), arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminCreateService(arg0, arg1, to_candid_ServiceCategory_n6(this._uploadFile, this._downloadFile, arg2), arg3);
            return result;
        }
    }
    async adminDeleteService(arg0: bigint): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.adminDeleteService(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminDeleteService(arg0);
            return result;
        }
    }
    async adminGetAllWalletStats(): Promise<{
        totalVolume: bigint;
        pendingWithdrawals: bigint;
        totalUsers: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetAllWalletStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetAllWalletStats();
            return result;
        }
    }
    async adminRejectPatient(arg0: Principal): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.adminRejectPatient(arg0);
                return from_candid_Result_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminRejectPatient(arg0);
            return from_candid_Result_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminUpdateArticle(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: string, arg5: Array<string>, arg6: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.adminUpdateArticle(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return from_candid_Result_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminUpdateArticle(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return from_candid_Result_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminUpdatePharmacyStock(arg0: bigint, arg1: Array<DrugStock>): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.adminUpdatePharmacyStock(arg0, arg1);
                return from_candid_Result_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminUpdatePharmacyStock(arg0, arg1);
            return from_candid_Result_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminUpdatePricing(arg0: bigint, arg1: bigint, arg2: bigint): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.adminUpdatePricing(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminUpdatePricing(arg0, arg1, arg2);
            return result;
        }
    }
    async adminUpdateService(arg0: bigint, arg1: string, arg2: string, arg3: bigint): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.adminUpdateService(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminUpdateService(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async approveNurse(arg0: Principal): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.approveNurse(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveNurse(arg0);
            return result;
        }
    }
    async cancelBooking(arg0: bigint): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.cancelBooking(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cancelBooking(arg0);
            return result;
        }
    }
    async createBooking(arg0: bigint, arg1: string, arg2: string, arg3: number, arg4: number, arg5: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createBooking(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBooking(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async deleteUser(arg0: string): Promise<Variant_ok_notFound_unauthorized> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteUser(arg0);
                return from_candid_variant_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteUser(arg0);
            return from_candid_variant_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async deposit(arg0: bigint, arg1: DepositMethod): Promise<{
        __kind__: "ok";
        ok: WalletBalance;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.deposit(arg0, to_candid_DepositMethod_n9(this._uploadFile, this._downloadFile, arg1));
                return from_candid_variant_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deposit(arg0, to_candid_DepositMethod_n9(this._uploadFile, this._downloadFile, arg1));
            return from_candid_variant_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async estimateCost(arg0: bigint, arg1: number, arg2: boolean, arg3: boolean): Promise<bigint | null> {
        if (this.processError) {
            try {
                const result = await this.actor.estimateCost(arg0, arg1, arg2, arg3);
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.estimateCost(arg0, arg1, arg2, arg3);
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getActivityLog(arg0: bigint, arg1: bigint): Promise<Array<ActivityEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActivityLog(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActivityLog(arg0, arg1);
            return result;
        }
    }
    async getAdminFinancialReport(): Promise<{
        pendingWithdrawals: bigint;
        recentTransactions: Array<TransactionEntry>;
        totalWithdrawals: bigint;
        totalRevenue: bigint;
        transactionCount: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminFinancialReport();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminFinancialReport();
            return result;
        }
    }
    async getAllBookings(): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllBookings();
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllBookings();
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllNurses(): Promise<Array<NurseProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllNurses();
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllNurses();
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllPatients(): Promise<Array<PatientProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPatients();
                return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPatients();
            return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getArticleBySlug(arg0: string): Promise<Article | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getArticleBySlug(arg0);
                return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getArticleBySlug(arg0);
            return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBookingStats(): Promise<BookingStats | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBookingStats();
                return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBookingStats();
            return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getIncomingBookings(): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getIncomingBookings();
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getIncomingBookings();
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyBalance(): Promise<WalletBalance> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyBalance();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyBalance();
            return result;
        }
    }
    async getMyBookings(): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyBookings();
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyBookings();
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyNurseProfile(): Promise<NurseProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyNurseProfile();
                return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyNurseProfile();
            return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyPatientProfile(): Promise<PatientProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyPatientProfile();
                return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyPatientProfile();
            return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyRole(): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyRole();
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyRole();
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyTransactionHistory(): Promise<Array<WalletTransaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyTransactionHistory();
                return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyTransactionHistory();
            return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNearbyNurses(arg0: number, arg1: number, arg2: number): Promise<Array<NurseProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNearbyNurses(arg0, arg1, arg2);
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNearbyNurses(arg0, arg1, arg2);
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNurseProfile(arg0: Principal): Promise<NurseProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getNurseProfile(arg0);
                return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNurseProfile(arg0);
            return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNurseSchedule(): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNurseSchedule();
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNurseSchedule();
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPendingNurses(): Promise<Array<NurseProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPendingNurses();
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPendingNurses();
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPendingPatients(): Promise<Array<PatientSummary>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPendingPatients();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPendingPatients();
            return result;
        }
    }
    async getPharmacies(): Promise<Array<Pharmacy>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPharmacies();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPharmacies();
            return result;
        }
    }
    async getPharmacyDrugs(arg0: bigint): Promise<Array<DrugStock>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPharmacyDrugs(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPharmacyDrugs(arg0);
            return result;
        }
    }
    async getPharmacyStock(arg0: bigint): Promise<Array<DrugStock> | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPharmacyStock(arg0);
                return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPharmacyStock(arg0);
            return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPlatformSettings(): Promise<PlatformSettings> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlatformSettings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlatformSettings();
            return result;
        }
    }
    async getPricingAuditLog(): Promise<Array<PricingAuditEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPricingAuditLog();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPricingAuditLog();
            return result;
        }
    }
    async getPricingConfig(): Promise<PricingConfig> {
        if (this.processError) {
            try {
                const result = await this.actor.getPricingConfig();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPricingConfig();
            return result;
        }
    }
    async getUserList(arg0: string | null, arg1: string | null): Promise<Array<UserListEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserList(to_candid_opt_n42(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n42(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserList(to_candid_opt_n42(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n42(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async listAllServices(): Promise<Array<Service>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAllServices();
                return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAllServices();
            return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async listArticles(arg0: bigint, arg1: bigint): Promise<{
        total: bigint;
        items: Array<Article>;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.listArticles(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listArticles(arg0, arg1);
            return result;
        }
    }
    async listServices(): Promise<Array<Service>> {
        if (this.processError) {
            try {
                const result = await this.actor.listServices();
                return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listServices();
            return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async loginWithEmail(arg0: string, arg1: string): Promise<Result_1> {
        if (this.processError) {
            try {
                const result = await this.actor.loginWithEmail(arg0, arg1);
                return from_candid_Result_1_n48(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.loginWithEmail(arg0, arg1);
            return from_candid_Result_1_n48(this._uploadFile, this._downloadFile, result);
        }
    }
    async registerAsAdmin(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.registerAsAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerAsAdmin();
            return result;
        }
    }
    async registerAsNurse(arg0: string, arg1: string, arg2: string, arg3: string | null, arg4: string, arg5: string, arg6: string, arg7: bigint, arg8: string | null, arg9: string, arg10: string, arg11: bigint, arg12: string, arg13: string, arg14: bigint, arg15: string, arg16: string, arg17: string, arg18: string, arg19: string, arg20: string | null, arg21: string | null, arg22: string | null): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.registerAsNurse(arg0, arg1, arg2, to_candid_opt_n42(this._uploadFile, this._downloadFile, arg3), arg4, arg5, arg6, arg7, to_candid_opt_n42(this._uploadFile, this._downloadFile, arg8), arg9, arg10, arg11, arg12, arg13, arg14, arg15, arg16, arg17, arg18, arg19, to_candid_opt_n42(this._uploadFile, this._downloadFile, arg20), to_candid_opt_n42(this._uploadFile, this._downloadFile, arg21), to_candid_opt_n42(this._uploadFile, this._downloadFile, arg22));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerAsNurse(arg0, arg1, arg2, to_candid_opt_n42(this._uploadFile, this._downloadFile, arg3), arg4, arg5, arg6, arg7, to_candid_opt_n42(this._uploadFile, this._downloadFile, arg8), arg9, arg10, arg11, arg12, arg13, arg14, arg15, arg16, arg17, arg18, arg19, to_candid_opt_n42(this._uploadFile, this._downloadFile, arg20), to_candid_opt_n42(this._uploadFile, this._downloadFile, arg21), to_candid_opt_n42(this._uploadFile, this._downloadFile, arg22));
            return result;
        }
    }
    async registerAsPatient(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.registerAsPatient();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerAsPatient();
            return result;
        }
    }
    async rejectBooking(arg0: bigint): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectBooking(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectBooking(arg0);
            return result;
        }
    }
    async rejectNurse(arg0: Principal): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectNurse(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectNurse(arg0);
            return result;
        }
    }
    async requestWithdrawal(arg0: bigint, arg1: WithdrawalMethod, arg2: string): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.requestWithdrawal(arg0, to_candid_WithdrawalMethod_n50(this._uploadFile, this._downloadFile, arg1), arg2);
                return from_candid_variant_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.requestWithdrawal(arg0, to_candid_WithdrawalMethod_n50(this._uploadFile, this._downloadFile, arg1), arg2);
            return from_candid_variant_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveEmailPassword(arg0: string, arg1: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.saveEmailPassword(arg0, arg1);
                return from_candid_Result_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveEmailPassword(arg0, arg1);
            return from_candid_Result_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveNurseProfile(arg0: string, arg1: string, arg2: string, arg3: string | null, arg4: string, arg5: string, arg6: string, arg7: bigint, arg8: string | null, arg9: string, arg10: string, arg11: bigint, arg12: string, arg13: string, arg14: bigint, arg15: string, arg16: string, arg17: string, arg18: string, arg19: string, arg20: string | null, arg21: string | null, arg22: string | null): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.saveNurseProfile(arg0, arg1, arg2, to_candid_opt_n42(this._uploadFile, this._downloadFile, arg3), arg4, arg5, arg6, arg7, to_candid_opt_n42(this._uploadFile, this._downloadFile, arg8), arg9, arg10, arg11, arg12, arg13, arg14, arg15, arg16, arg17, arg18, arg19, to_candid_opt_n42(this._uploadFile, this._downloadFile, arg20), to_candid_opt_n42(this._uploadFile, this._downloadFile, arg21), to_candid_opt_n42(this._uploadFile, this._downloadFile, arg22));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveNurseProfile(arg0, arg1, arg2, to_candid_opt_n42(this._uploadFile, this._downloadFile, arg3), arg4, arg5, arg6, arg7, to_candid_opt_n42(this._uploadFile, this._downloadFile, arg8), arg9, arg10, arg11, arg12, arg13, arg14, arg15, arg16, arg17, arg18, arg19, to_candid_opt_n42(this._uploadFile, this._downloadFile, arg20), to_candid_opt_n42(this._uploadFile, this._downloadFile, arg21), to_candid_opt_n42(this._uploadFile, this._downloadFile, arg22));
            return result;
        }
    }
    async savePatientProfile(arg0: string, arg1: string, arg2: string, arg3: bigint, arg4: string, arg5: string, arg6: string, arg7: string, arg8: string, arg9: string, arg10: string | null, arg11: string | null, arg12: string, arg13: string, arg14: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.savePatientProfile(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, to_candid_opt_n42(this._uploadFile, this._downloadFile, arg10), to_candid_opt_n42(this._uploadFile, this._downloadFile, arg11), arg12, arg13, arg14);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.savePatientProfile(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, to_candid_opt_n42(this._uploadFile, this._downloadFile, arg10), to_candid_opt_n42(this._uploadFile, this._downloadFile, arg11), arg12, arg13, arg14);
            return result;
        }
    }
    async searchArticles(arg0: string, arg1: bigint, arg2: bigint): Promise<{
        total: bigint;
        items: Array<Article>;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.searchArticles(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchArticles(arg0, arg1, arg2);
            return result;
        }
    }
    async seedArticles(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.seedArticles();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.seedArticles();
            return result;
        }
    }
    async seedDefaultServices(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.seedDefaultServices();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.seedDefaultServices();
            return result;
        }
    }
    async seedPharmacies(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.seedPharmacies();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.seedPharmacies();
            return result;
        }
    }
    async submitVisitReport(arg0: bigint, arg1: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.submitVisitReport(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitVisitReport(arg0, arg1);
            return result;
        }
    }
    async suspendUser(arg0: string, arg1: string): Promise<Variant_ok_notFound_unauthorized> {
        if (this.processError) {
            try {
                const result = await this.actor.suspendUser(arg0, arg1);
                return from_candid_variant_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.suspendUser(arg0, arg1);
            return from_candid_variant_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async transferBalance(arg0: Principal, arg1: bigint): Promise<{
        __kind__: "ok";
        ok: string;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.transferBalance(arg0, arg1);
                return from_candid_variant_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transferBalance(arg0, arg1);
            return from_candid_variant_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateNurseLocation(arg0: number, arg1: number): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.updateNurseLocation(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateNurseLocation(arg0, arg1);
            return result;
        }
    }
    async updatePlatformSettings(arg0: PlatformSettings): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePlatformSettings(arg0);
                return from_candid_Result_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePlatformSettings(arg0);
            return from_candid_Result_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async verifyEmailPassword(arg0: string, arg1: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.verifyEmailPassword(arg0, arg1);
                return from_candid_Result_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifyEmailPassword(arg0, arg1);
            return from_candid_Result_n4(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_BookingStatus_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BookingStatus): BookingStatus {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_Booking_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Booking): Booking {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_NurseProfile_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NurseProfile): NurseProfile {
    return from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_NurseStatus_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NurseStatus): NurseStatus {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid_PatientProfile_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PatientProfile): PatientProfile {
    return from_candid_record_n29(_uploadFile, _downloadFile, value);
}
function from_candid_Result_1_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_1): Result_1 {
    return from_candid_variant_n49(_uploadFile, _downloadFile, value);
}
function from_candid_Result_2_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_2): Result_2 {
    return from_candid_variant_n3(_uploadFile, _downloadFile, value);
}
function from_candid_Result_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result): Result {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_ServiceCategory_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ServiceCategory): ServiceCategory {
    return from_candid_variant_n47(_uploadFile, _downloadFile, value);
}
function from_candid_Service_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Service): Service {
    return from_candid_record_n45(_uploadFile, _downloadFile, value);
}
function from_candid_TransactionStatus_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TransactionStatus): TransactionStatus {
    return from_candid_variant_n38(_uploadFile, _downloadFile, value);
}
function from_candid_TransactionType_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TransactionType): TransactionType {
    return from_candid_variant_n40(_uploadFile, _downloadFile, value);
}
function from_candid_WalletTransaction_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WalletTransaction): WalletTransaction {
    return from_candid_record_n36(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [number]): number | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Article]): Article | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_BookingStats]): BookingStats | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_NurseProfile]): NurseProfile | null {
    return value.length === 0 ? null : from_candid_NurseProfile_n21(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PatientProfile]): PatientProfile | null {
    return value.length === 0 ? null : from_candid_PatientProfile_n28(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Array<_DrugStock>]): Array<DrugStock> | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _BookingStatus;
    latitude: number;
    scheduledDate: string;
    scheduledTime: string;
    nursePrincipal: [] | [Principal];
    createdAt: bigint;
    estimatedFeeIdr: bigint;
    updatedAt: bigint;
    visitReport: [] | [string];
    patientPrincipal: Principal;
    longitude: number;
    notes: string;
    serviceId: bigint;
}): {
    id: bigint;
    status: BookingStatus;
    latitude: number;
    scheduledDate: string;
    scheduledTime: string;
    nursePrincipal?: Principal;
    createdAt: bigint;
    estimatedFeeIdr: bigint;
    updatedAt: bigint;
    visitReport?: string;
    patientPrincipal: Principal;
    longitude: number;
    notes: string;
    serviceId: bigint;
} {
    return {
        id: value.id,
        status: from_candid_BookingStatus_n16(_uploadFile, _downloadFile, value.status),
        latitude: value.latitude,
        scheduledDate: value.scheduledDate,
        scheduledTime: value.scheduledTime,
        nursePrincipal: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.nursePrincipal)),
        createdAt: value.createdAt,
        estimatedFeeIdr: value.estimatedFeeIdr,
        updatedAt: value.updatedAt,
        visitReport: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.visitReport)),
        patientPrincipal: value.patientPrincipal,
        longitude: value.longitude,
        notes: value.notes,
        serviceId: value.serviceId
    };
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    previousWorkHistory: [] | [string];
    status: _NurseStatus;
    latitude: [] | [number];
    strNumber: string;
    principal: Principal;
    emergencyCertExpiry: [] | [string];
    strExpiry: [] | [string];
    locationUpdatedAt: [] | [bigint];
    name: string;
    createdAt: bigint;
    profession: [] | [string];
    currentWorkDuration: [] | [bigint];
    graduationYear: [] | [bigint];
    strDocumentUrl: [] | [string];
    previousFacilityType: [] | [string];
    email: [] | [string];
    totalExperienceYears: [] | [bigint];
    university: [] | [string];
    additionalCertificates: [] | [string];
    ktpPhotoUrl: [] | [string];
    updatedAt: bigint;
    experienceYears: bigint;
    strDocUrl: string;
    currentFacilityType: [] | [string];
    longitude: [] | [number];
    ijazahDocumentUrl: [] | [string];
    ktpDocUrl: string;
    specialization: string;
    medicalCompetencies: [] | [string];
    passwordHash: [] | [string];
    selfieWithKtpUrl: [] | [string];
    emergencyCertification: [] | [string];
    employeeIdCardUrl: [] | [string];
    currentWorkplace: [] | [string];
    professionalOrg: [] | [string];
}): {
    previousWorkHistory?: string;
    status: NurseStatus;
    latitude?: number;
    strNumber: string;
    principal: Principal;
    emergencyCertExpiry?: string;
    strExpiry?: string;
    locationUpdatedAt?: bigint;
    name: string;
    createdAt: bigint;
    profession?: string;
    currentWorkDuration?: bigint;
    graduationYear?: bigint;
    strDocumentUrl?: string;
    previousFacilityType?: string;
    email?: string;
    totalExperienceYears?: bigint;
    university?: string;
    additionalCertificates?: string;
    ktpPhotoUrl?: string;
    updatedAt: bigint;
    experienceYears: bigint;
    strDocUrl: string;
    currentFacilityType?: string;
    longitude?: number;
    ijazahDocumentUrl?: string;
    ktpDocUrl: string;
    specialization: string;
    medicalCompetencies?: string;
    passwordHash?: string;
    selfieWithKtpUrl?: string;
    emergencyCertification?: string;
    employeeIdCardUrl?: string;
    currentWorkplace?: string;
    professionalOrg?: string;
} {
    return {
        previousWorkHistory: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.previousWorkHistory)),
        status: from_candid_NurseStatus_n23(_uploadFile, _downloadFile, value.status),
        latitude: record_opt_to_undefined(from_candid_opt_n25(_uploadFile, _downloadFile, value.latitude)),
        strNumber: value.strNumber,
        principal: value.principal,
        emergencyCertExpiry: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.emergencyCertExpiry)),
        strExpiry: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.strExpiry)),
        locationUpdatedAt: record_opt_to_undefined(from_candid_opt_n26(_uploadFile, _downloadFile, value.locationUpdatedAt)),
        name: value.name,
        createdAt: value.createdAt,
        profession: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.profession)),
        currentWorkDuration: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.currentWorkDuration)),
        graduationYear: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.graduationYear)),
        strDocumentUrl: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.strDocumentUrl)),
        previousFacilityType: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.previousFacilityType)),
        email: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.email)),
        totalExperienceYears: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.totalExperienceYears)),
        university: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.university)),
        additionalCertificates: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.additionalCertificates)),
        ktpPhotoUrl: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.ktpPhotoUrl)),
        updatedAt: value.updatedAt,
        experienceYears: value.experienceYears,
        strDocUrl: value.strDocUrl,
        currentFacilityType: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.currentFacilityType)),
        longitude: record_opt_to_undefined(from_candid_opt_n25(_uploadFile, _downloadFile, value.longitude)),
        ijazahDocumentUrl: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.ijazahDocumentUrl)),
        ktpDocUrl: value.ktpDocUrl,
        specialization: value.specialization,
        medicalCompetencies: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.medicalCompetencies)),
        passwordHash: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.passwordHash)),
        selfieWithKtpUrl: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.selfieWithKtpUrl)),
        emergencyCertification: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.emergencyCertification)),
        employeeIdCardUrl: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.employeeIdCardUrl)),
        currentWorkplace: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.currentWorkplace)),
        professionalOrg: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.professionalOrg))
    };
}
function from_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    age: bigint;
    nik: [] | [string];
    principal: Principal;
    bloodType: string;
    birthDate: [] | [string];
    name: string;
    createdAt: bigint;
    email: [] | [string];
    emergencyContactRelation: [] | [string];
    ktpPhotoUrl: [] | [string];
    updatedAt: bigint;
    address: [] | [string];
    gender: [] | [string];
    emergencyContactPhone: [] | [string];
    conditions: string;
    passwordHash: [] | [string];
    emergencyContactName: [] | [string];
    selfieWithKtpUrl: [] | [string];
    phoneNumber: [] | [string];
    allergies: string;
    verificationStatus: string;
}): {
    age: bigint;
    nik?: string;
    principal: Principal;
    bloodType: string;
    birthDate?: string;
    name: string;
    createdAt: bigint;
    email?: string;
    emergencyContactRelation?: string;
    ktpPhotoUrl?: string;
    updatedAt: bigint;
    address?: string;
    gender?: string;
    emergencyContactPhone?: string;
    conditions: string;
    passwordHash?: string;
    emergencyContactName?: string;
    selfieWithKtpUrl?: string;
    phoneNumber?: string;
    allergies: string;
    verificationStatus: string;
} {
    return {
        age: value.age,
        nik: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.nik)),
        principal: value.principal,
        bloodType: value.bloodType,
        birthDate: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.birthDate)),
        name: value.name,
        createdAt: value.createdAt,
        email: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.email)),
        emergencyContactRelation: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.emergencyContactRelation)),
        ktpPhotoUrl: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.ktpPhotoUrl)),
        updatedAt: value.updatedAt,
        address: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.address)),
        gender: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.gender)),
        emergencyContactPhone: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.emergencyContactPhone)),
        conditions: value.conditions,
        passwordHash: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.passwordHash)),
        emergencyContactName: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.emergencyContactName)),
        selfieWithKtpUrl: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.selfieWithKtpUrl)),
        phoneNumber: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.phoneNumber)),
        allergies: value.allergies,
        verificationStatus: value.verificationStatus
    };
}
function from_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _TransactionStatus;
    transactionType: _TransactionType;
    userId: Principal;
    createdAt: bigint;
    description: string;
    currency: string;
    amount: bigint;
}): {
    id: bigint;
    status: TransactionStatus;
    transactionType: TransactionType;
    userId: Principal;
    createdAt: bigint;
    description: string;
    currency: string;
    amount: bigint;
} {
    return {
        id: value.id,
        status: from_candid_TransactionStatus_n37(_uploadFile, _downloadFile, value.status),
        transactionType: from_candid_TransactionType_n39(_uploadFile, _downloadFile, value.transactionType),
        userId: value.userId,
        createdAt: value.createdAt,
        description: value.description,
        currency: value.currency,
        amount: value.amount
    };
}
function from_candid_record_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    baseFeeIdr: bigint;
    name: string;
    createdAt: bigint;
    description: string;
    isActive: boolean;
    updatedAt: bigint;
    category: _ServiceCategory;
}): {
    id: bigint;
    baseFeeIdr: bigint;
    name: string;
    createdAt: bigint;
    description: string;
    isActive: boolean;
    updatedAt: bigint;
    category: ServiceCategory;
} {
    return {
        id: value.id,
        baseFeeIdr: value.baseFeeIdr,
        name: value.name,
        createdAt: value.createdAt,
        description: value.description,
        isActive: value.isActive,
        updatedAt: value.updatedAt,
        category: from_candid_ServiceCategory_n46(_uploadFile, _downloadFile, value.category)
    };
}
function from_candid_variant_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    notFound: null;
}): Variant_ok_notFound {
    return "ok" in value ? Variant_ok_notFound.ok : "notFound" in value ? Variant_ok_notFound.notFound : value;
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _WalletBalance;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: WalletBalance;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cancelled: null;
} | {
    pending: null;
} | {
    in_progress: null;
} | {
    completed: null;
} | {
    rejected: null;
} | {
    accepted: null;
}): BookingStatus {
    return "cancelled" in value ? BookingStatus.cancelled : "pending" in value ? BookingStatus.pending : "in_progress" in value ? BookingStatus.in_progress : "completed" in value ? BookingStatus.completed : "rejected" in value ? BookingStatus.rejected : "accepted" in value ? BookingStatus.accepted : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    verified: null;
} | {
    pending_verification: null;
} | {
    rejected: null;
}): NurseStatus {
    return "verified" in value ? NurseStatus.verified : "pending_verification" in value ? NurseStatus.pending_verification : "rejected" in value ? NurseStatus.rejected : value;
}
function from_candid_variant_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: bigint;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: bigint;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    completed: null;
} | {
    failed: null;
}): TransactionStatus {
    return "pending" in value ? TransactionStatus.pending : "completed" in value ? TransactionStatus.completed : "failed" in value ? TransactionStatus.failed : value;
}
function from_candid_variant_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    transfer_out: null;
} | {
    deposit: null;
} | {
    transfer_in: null;
} | {
    withdrawal: null;
} | {
    service_income: null;
} | {
    service_payment: null;
}): TransactionType {
    return "transfer_out" in value ? TransactionType.transfer_out : "deposit" in value ? TransactionType.deposit : "transfer_in" in value ? TransactionType.transfer_in : "withdrawal" in value ? TransactionType.withdrawal : "service_income" in value ? TransactionType.service_income : "service_payment" in value ? TransactionType.service_payment : value;
}
function from_candid_variant_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    postopcare: null;
} | {
    ambulance: null;
} | {
    elderlycare: null;
} | {
    woundcare: null;
} | {
    physiotherapy: null;
}): ServiceCategory {
    return "postopcare" in value ? ServiceCategory.postopcare : "ambulance" in value ? ServiceCategory.ambulance : "elderlycare" in value ? ServiceCategory.elderlycare : "woundcare" in value ? ServiceCategory.woundcare : "physiotherapy" in value ? ServiceCategory.physiotherapy : value;
}
function from_candid_variant_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: {
        role: string;
    };
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: {
        role: string;
    };
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: string;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    notFound: null;
} | {
    unauthorized: null;
}): Variant_ok_notFound_unauthorized {
    return "ok" in value ? Variant_ok_notFound_unauthorized.ok : "notFound" in value ? Variant_ok_notFound_unauthorized.notFound : "unauthorized" in value ? Variant_ok_notFound_unauthorized.unauthorized : value;
}
function from_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Booking>): Array<Booking> {
    return value.map((x)=>from_candid_Booking_n14(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_NurseProfile>): Array<NurseProfile> {
    return value.map((x)=>from_candid_NurseProfile_n21(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PatientProfile>): Array<PatientProfile> {
    return value.map((x)=>from_candid_PatientProfile_n28(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_WalletTransaction>): Array<WalletTransaction> {
    return value.map((x)=>from_candid_WalletTransaction_n35(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Service>): Array<Service> {
    return value.map((x)=>from_candid_Service_n44(_uploadFile, _downloadFile, x));
}
function to_candid_DepositMethod_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DepositMethod): _DepositMethod {
    return to_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function to_candid_ServiceCategory_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ServiceCategory): _ServiceCategory {
    return to_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function to_candid_WithdrawalMethod_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: WithdrawalMethod): _WithdrawalMethod {
    return to_candid_variant_n51(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DepositMethod): {
    ovo: null;
} | {
    dana: null;
} | {
    va_bca: null;
} | {
    va_bni: null;
} | {
    va_bri: null;
} | {
    va_mandiri: null;
} {
    return value == DepositMethod.ovo ? {
        ovo: null
    } : value == DepositMethod.dana ? {
        dana: null
    } : value == DepositMethod.va_bca ? {
        va_bca: null
    } : value == DepositMethod.va_bni ? {
        va_bni: null
    } : value == DepositMethod.va_bri ? {
        va_bri: null
    } : value == DepositMethod.va_mandiri ? {
        va_mandiri: null
    } : value;
}
function to_candid_variant_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: WithdrawalMethod): {
    ovo: null;
} | {
    bank_mandiri: null;
} | {
    dana: null;
} | {
    bank_bca: null;
} | {
    bank_bni: null;
} | {
    bank_bri: null;
} {
    return value == WithdrawalMethod.ovo ? {
        ovo: null
    } : value == WithdrawalMethod.bank_mandiri ? {
        bank_mandiri: null
    } : value == WithdrawalMethod.dana ? {
        dana: null
    } : value == WithdrawalMethod.bank_bca ? {
        bank_bca: null
    } : value == WithdrawalMethod.bank_bni ? {
        bank_bni: null
    } : value == WithdrawalMethod.bank_bri ? {
        bank_bri: null
    } : value;
}
function to_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ServiceCategory): {
    postopcare: null;
} | {
    ambulance: null;
} | {
    elderlycare: null;
} | {
    woundcare: null;
} | {
    physiotherapy: null;
} {
    return value == ServiceCategory.postopcare ? {
        postopcare: null
    } : value == ServiceCategory.ambulance ? {
        ambulance: null
    } : value == ServiceCategory.elderlycare ? {
        elderlycare: null
    } : value == ServiceCategory.woundcare ? {
        woundcare: null
    } : value == ServiceCategory.physiotherapy ? {
        physiotherapy: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
