/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface PricingConfig {
    nightSurchargePct: bigint;
    holidaySurchargePct: bigint;
    updatedAt: bigint;
    perKmRateIdr: bigint;
}
export interface PatientProfile {
    age: bigint;
    principal: Principal;
    bloodType: string;
    name: string;
    createdAt: bigint;
    emergencyContact: string;
    updatedAt: bigint;
    conditions: string;
    allergies: string;
}
export interface Service {
    id: bigint;
    baseFeeIdr: bigint;
    name: string;
    createdAt: bigint;
    description: string;
    isActive: boolean;
    updatedAt: bigint;
    category: ServiceCategory;
}
export interface PricingAuditEntry {
    id: bigint;
    changedAt: bigint;
    adminPrincipal: Principal;
    changeDescription: string;
}
export interface NurseProfile {
    status: NurseStatus;
    latitude?: number;
    strNumber: string;
    principal: Principal;
    locationUpdatedAt?: bigint;
    name: string;
    createdAt: bigint;
    updatedAt: bigint;
    experienceYears: bigint;
    strDocUrl: string;
    longitude?: number;
    ktpDocUrl: string;
    specialization: string;
}
export interface Booking {
    id: bigint;
    status: BookingStatus;
    latitude: number;
    scheduledDate: string;
    scheduledTime: string;
    nursePrincipal?: Principal;
    createdAt: bigint;
    estimatedFeeIdr: bigint;
    updatedAt: bigint;
    visitReport?: string;
    patientPrincipal: Principal;
    longitude: number;
    notes: string;
    serviceId: bigint;
}
export interface BookingStats {
    total: bigint;
    cancelled: bigint;
    pending: bigint;
    in_progress: bigint;
    completed: bigint;
    rejected: bigint;
    accepted: bigint;
}
export enum BookingStatus {
    cancelled = "cancelled",
    pending = "pending",
    in_progress = "in_progress",
    completed = "completed",
    rejected = "rejected",
    accepted = "accepted"
}
export enum NurseStatus {
    verified = "verified",
    pending_verification = "pending_verification",
    rejected = "rejected"
}
export enum ServiceCategory {
    postopcare = "postopcare",
    ambulance = "ambulance",
    elderlycare = "elderlycare",
    woundcare = "woundcare",
    physiotherapy = "physiotherapy"
}
export interface backendInterface {
    acceptBooking(bookingId: bigint): Promise<string>;
    adminCreateService(name: string, description: string, category: ServiceCategory, baseFeeIdr: bigint): Promise<string>;
    adminDeleteService(id: bigint): Promise<string>;
    adminUpdatePricing(perKmRateIdr: bigint, nightSurchargePct: bigint, holidaySurchargePct: bigint): Promise<string>;
    adminUpdateService(id: bigint, name: string, description: string, baseFeeIdr: bigint): Promise<string>;
    approveNurse(nursePrincipal: Principal): Promise<string>;
    cancelBooking(bookingId: bigint): Promise<string>;
    createBooking(serviceId: bigint, scheduledDate: string, scheduledTime: string, latitude: number, longitude: number, notes: string): Promise<string>;
    estimateCost(serviceId: bigint, distanceKm: number, nightTime: boolean, holiday: boolean): Promise<bigint | null>;
    getAllBookings(): Promise<Array<Booking>>;
    getAllNurses(): Promise<Array<NurseProfile>>;
    getBookingStats(): Promise<BookingStats | null>;
    getIncomingBookings(): Promise<Array<Booking>>;
    getMyBookings(): Promise<Array<Booking>>;
    getMyNurseProfile(): Promise<NurseProfile | null>;
    getMyPatientProfile(): Promise<PatientProfile | null>;
    getMyRole(): Promise<string | null>;
    getNearbyNurses(lat: number, lon: number, radiusKm: number): Promise<Array<NurseProfile>>;
    getNurseProfile(p: Principal): Promise<NurseProfile | null>;
    getNurseSchedule(): Promise<Array<Booking>>;
    getPendingNurses(): Promise<Array<NurseProfile>>;
    getPricingAuditLog(): Promise<Array<PricingAuditEntry>>;
    getPricingConfig(): Promise<PricingConfig>;
    listAllServices(): Promise<Array<Service>>;
    listServices(): Promise<Array<Service>>;
    registerAsAdmin(): Promise<string>;
    registerAsNurse(name: string, strNumber: string, specialization: string, experienceYears: bigint, strDocUrl: string, ktpDocUrl: string): Promise<string>;
    registerAsPatient(): Promise<string>;
    rejectBooking(bookingId: bigint): Promise<string>;
    rejectNurse(nursePrincipal: Principal): Promise<string>;
    saveNurseProfile(name: string, strNumber: string, specialization: string, experienceYears: bigint, strDocUrl: string, ktpDocUrl: string): Promise<string>;
    savePatientProfile(name: string, age: bigint, conditions: string, allergies: string, bloodType: string, emergencyContact: string): Promise<string>;
    seedDefaultServices(): Promise<string>;
    submitVisitReport(bookingId: bigint, reportText: string): Promise<string>;
    updateNurseLocation(lat: number, lon: number): Promise<string>;
}
import type { Booking as _Booking, BookingStats as _BookingStats, BookingStatus as _BookingStatus, NurseProfile as _NurseProfile, NurseStatus as _NurseStatus, PatientProfile as _PatientProfile, Service as _Service, ServiceCategory as _ServiceCategory } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async acceptBooking(arg0: bigint): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.acceptBooking(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.acceptBooking(arg0);
            return result;
        }
    }
    async adminCreateService(arg0: string, arg1: string, arg2: ServiceCategory, arg3: bigint): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.adminCreateService(arg0, arg1, to_candid_ServiceCategory_n1(this._uploadFile, this._downloadFile, arg2), arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminCreateService(arg0, arg1, to_candid_ServiceCategory_n1(this._uploadFile, this._downloadFile, arg2), arg3);
            return result;
        }
    }
    async adminDeleteService(arg0: bigint): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.adminDeleteService(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminDeleteService(arg0);
            return result;
        }
    }
    async adminUpdatePricing(arg0: bigint, arg1: bigint, arg2: bigint): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.adminUpdatePricing(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminUpdatePricing(arg0, arg1, arg2);
            return result;
        }
    }
    async adminUpdateService(arg0: bigint, arg1: string, arg2: string, arg3: bigint): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.adminUpdateService(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminUpdateService(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async approveNurse(arg0: Principal): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.approveNurse(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveNurse(arg0);
            return result;
        }
    }
    async cancelBooking(arg0: bigint): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.cancelBooking(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cancelBooking(arg0);
            return result;
        }
    }
    async createBooking(arg0: bigint, arg1: string, arg2: string, arg3: number, arg4: number, arg5: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createBooking(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBooking(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async estimateCost(arg0: bigint, arg1: number, arg2: boolean, arg3: boolean): Promise<bigint | null> {
        if (this.processError) {
            try {
                const result = await this.actor.estimateCost(arg0, arg1, arg2, arg3);
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.estimateCost(arg0, arg1, arg2, arg3);
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllBookings(): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllBookings();
                return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllBookings();
            return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllNurses(): Promise<Array<NurseProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllNurses();
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllNurses();
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBookingStats(): Promise<BookingStats | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBookingStats();
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBookingStats();
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getIncomingBookings(): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getIncomingBookings();
                return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getIncomingBookings();
            return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyBookings(): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyBookings();
                return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyBookings();
            return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyNurseProfile(): Promise<NurseProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyNurseProfile();
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyNurseProfile();
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyPatientProfile(): Promise<PatientProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyPatientProfile();
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyPatientProfile();
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyRole(): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyRole();
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyRole();
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNearbyNurses(arg0: number, arg1: number, arg2: number): Promise<Array<NurseProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNearbyNurses(arg0, arg1, arg2);
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNearbyNurses(arg0, arg1, arg2);
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNurseProfile(arg0: Principal): Promise<NurseProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getNurseProfile(arg0);
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNurseProfile(arg0);
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNurseSchedule(): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNurseSchedule();
                return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNurseSchedule();
            return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPendingNurses(): Promise<Array<NurseProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPendingNurses();
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPendingNurses();
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPricingAuditLog(): Promise<Array<PricingAuditEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPricingAuditLog();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPricingAuditLog();
            return result;
        }
    }
    async getPricingConfig(): Promise<PricingConfig> {
        if (this.processError) {
            try {
                const result = await this.actor.getPricingConfig();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPricingConfig();
            return result;
        }
    }
    async listAllServices(): Promise<Array<Service>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAllServices();
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAllServices();
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async listServices(): Promise<Array<Service>> {
        if (this.processError) {
            try {
                const result = await this.actor.listServices();
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listServices();
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async registerAsAdmin(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.registerAsAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerAsAdmin();
            return result;
        }
    }
    async registerAsNurse(arg0: string, arg1: string, arg2: string, arg3: bigint, arg4: string, arg5: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.registerAsNurse(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerAsNurse(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async registerAsPatient(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.registerAsPatient();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerAsPatient();
            return result;
        }
    }
    async rejectBooking(arg0: bigint): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectBooking(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectBooking(arg0);
            return result;
        }
    }
    async rejectNurse(arg0: Principal): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectNurse(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectNurse(arg0);
            return result;
        }
    }
    async saveNurseProfile(arg0: string, arg1: string, arg2: string, arg3: bigint, arg4: string, arg5: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.saveNurseProfile(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveNurseProfile(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async savePatientProfile(arg0: string, arg1: bigint, arg2: string, arg3: string, arg4: string, arg5: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.savePatientProfile(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.savePatientProfile(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async seedDefaultServices(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.seedDefaultServices();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.seedDefaultServices();
            return result;
        }
    }
    async submitVisitReport(arg0: bigint, arg1: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.submitVisitReport(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitVisitReport(arg0, arg1);
            return result;
        }
    }
    async updateNurseLocation(arg0: number, arg1: number): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.updateNurseLocation(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateNurseLocation(arg0, arg1);
            return result;
        }
    }
}
function from_candid_BookingStatus_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BookingStatus): BookingStatus {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_Booking_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Booking): Booking {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_NurseProfile_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NurseProfile): NurseProfile {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_NurseStatus_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NurseStatus): NurseStatus {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_ServiceCategory_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ServiceCategory): ServiceCategory {
    return from_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function from_candid_Service_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Service): Service {
    return from_candid_record_n23(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [number]): number | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_BookingStats]): BookingStats | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_NurseProfile]): NurseProfile | null {
    return value.length === 0 ? null : from_candid_NurseProfile_n12(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PatientProfile]): PatientProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _NurseStatus;
    latitude: [] | [number];
    strNumber: string;
    principal: Principal;
    locationUpdatedAt: [] | [bigint];
    name: string;
    createdAt: bigint;
    updatedAt: bigint;
    experienceYears: bigint;
    strDocUrl: string;
    longitude: [] | [number];
    ktpDocUrl: string;
    specialization: string;
}): {
    status: NurseStatus;
    latitude?: number;
    strNumber: string;
    principal: Principal;
    locationUpdatedAt?: bigint;
    name: string;
    createdAt: bigint;
    updatedAt: bigint;
    experienceYears: bigint;
    strDocUrl: string;
    longitude?: number;
    ktpDocUrl: string;
    specialization: string;
} {
    return {
        status: from_candid_NurseStatus_n14(_uploadFile, _downloadFile, value.status),
        latitude: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.latitude)),
        strNumber: value.strNumber,
        principal: value.principal,
        locationUpdatedAt: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.locationUpdatedAt)),
        name: value.name,
        createdAt: value.createdAt,
        updatedAt: value.updatedAt,
        experienceYears: value.experienceYears,
        strDocUrl: value.strDocUrl,
        longitude: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.longitude)),
        ktpDocUrl: value.ktpDocUrl,
        specialization: value.specialization
    };
}
function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    baseFeeIdr: bigint;
    name: string;
    createdAt: bigint;
    description: string;
    isActive: boolean;
    updatedAt: bigint;
    category: _ServiceCategory;
}): {
    id: bigint;
    baseFeeIdr: bigint;
    name: string;
    createdAt: bigint;
    description: string;
    isActive: boolean;
    updatedAt: bigint;
    category: ServiceCategory;
} {
    return {
        id: value.id,
        baseFeeIdr: value.baseFeeIdr,
        name: value.name,
        createdAt: value.createdAt,
        description: value.description,
        isActive: value.isActive,
        updatedAt: value.updatedAt,
        category: from_candid_ServiceCategory_n24(_uploadFile, _downloadFile, value.category)
    };
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _BookingStatus;
    latitude: number;
    scheduledDate: string;
    scheduledTime: string;
    nursePrincipal: [] | [Principal];
    createdAt: bigint;
    estimatedFeeIdr: bigint;
    updatedAt: bigint;
    visitReport: [] | [string];
    patientPrincipal: Principal;
    longitude: number;
    notes: string;
    serviceId: bigint;
}): {
    id: bigint;
    status: BookingStatus;
    latitude: number;
    scheduledDate: string;
    scheduledTime: string;
    nursePrincipal?: Principal;
    createdAt: bigint;
    estimatedFeeIdr: bigint;
    updatedAt: bigint;
    visitReport?: string;
    patientPrincipal: Principal;
    longitude: number;
    notes: string;
    serviceId: bigint;
} {
    return {
        id: value.id,
        status: from_candid_BookingStatus_n7(_uploadFile, _downloadFile, value.status),
        latitude: value.latitude,
        scheduledDate: value.scheduledDate,
        scheduledTime: value.scheduledTime,
        nursePrincipal: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.nursePrincipal)),
        createdAt: value.createdAt,
        estimatedFeeIdr: value.estimatedFeeIdr,
        updatedAt: value.updatedAt,
        visitReport: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.visitReport)),
        patientPrincipal: value.patientPrincipal,
        longitude: value.longitude,
        notes: value.notes,
        serviceId: value.serviceId
    };
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    verified: null;
} | {
    pending_verification: null;
} | {
    rejected: null;
}): NurseStatus {
    return "verified" in value ? NurseStatus.verified : "pending_verification" in value ? NurseStatus.pending_verification : "rejected" in value ? NurseStatus.rejected : value;
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    postopcare: null;
} | {
    ambulance: null;
} | {
    elderlycare: null;
} | {
    woundcare: null;
} | {
    physiotherapy: null;
}): ServiceCategory {
    return "postopcare" in value ? ServiceCategory.postopcare : "ambulance" in value ? ServiceCategory.ambulance : "elderlycare" in value ? ServiceCategory.elderlycare : "woundcare" in value ? ServiceCategory.woundcare : "physiotherapy" in value ? ServiceCategory.physiotherapy : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cancelled: null;
} | {
    pending: null;
} | {
    in_progress: null;
} | {
    completed: null;
} | {
    rejected: null;
} | {
    accepted: null;
}): BookingStatus {
    return "cancelled" in value ? BookingStatus.cancelled : "pending" in value ? BookingStatus.pending : "in_progress" in value ? BookingStatus.in_progress : "completed" in value ? BookingStatus.completed : "rejected" in value ? BookingStatus.rejected : "accepted" in value ? BookingStatus.accepted : value;
}
function from_candid_vec_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_NurseProfile>): Array<NurseProfile> {
    return value.map((x)=>from_candid_NurseProfile_n12(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Service>): Array<Service> {
    return value.map((x)=>from_candid_Service_n22(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Booking>): Array<Booking> {
    return value.map((x)=>from_candid_Booking_n5(_uploadFile, _downloadFile, x));
}
function to_candid_ServiceCategory_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ServiceCategory): _ServiceCategory {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ServiceCategory): {
    postopcare: null;
} | {
    ambulance: null;
} | {
    elderlycare: null;
} | {
    woundcare: null;
} | {
    physiotherapy: null;
} {
    return value == ServiceCategory.postopcare ? {
        postopcare: null
    } : value == ServiceCategory.ambulance ? {
        ambulance: null
    } : value == ServiceCategory.elderlycare ? {
        elderlycare: null
    } : value == ServiceCategory.woundcare ? {
        woundcare: null
    } : value == ServiceCategory.physiotherapy ? {
        physiotherapy: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
